case class Offside(stitchId: String,
                   drugName: String,
                   umlsId: String,
                   event: String,
                   rr: Double,
                   log2rr: Double,
                   tStat: Double,
                   pValue: Double,
                   observed: Double,
                   expected: Double,
                   bgCorrection: Double,
                   sider: Double,
                   futureAers: Double,
                   medEffect: Double)
